dimagi/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    # path('',views.UserLocationView.as_view(), name='user-location'),
    path('users/',views.UserListView.as_view(), name='user-locations'),
    path('', views.UserFormView.as_view(), name='user-form')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dimagi/', include('dimagi.urls')),
]

dimagi/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    email = models.EmailField()
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=50, null=True, default='ma')
    country = models.CharField(max_length=100, blank=True, default='usa')
    timestamp = models.DateTimeField(auto_now_add=True, blank=True)
    lat = models.FloatField()
    lng = models.FloatField()

    def __str__(self):
        return f"{self.email} : {self.city} @ {self.timestamp}"

dimagi/forms.py
from django import forms

class UserForm(forms.Form):
    email = forms.EmailField()
    city = forms.CharField()
    state = forms.CharField(required=False)
    country = forms.CharField(required=False)

dimagi/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import generic
import django.forms
import requests
import traceback
from django.forms.utils import ErrorList
from .forms import UserForm
from .models import User
from .CityFinder import CityFinder
from .Tracker import Tracker


# def view1 (request):
#     users = User.objects.all()
#     return render(request,"dimagi/users.html",{'users_list':users})
#     # return HttpResponse("Hello")

class UserListView (generic.ListView):
    model = User
    template_name = "dimagi/users.html"

    # provides the ability to order by year in descending order
    def get_queryset(self):
        return User.objects.order_by('email')

class UserFormView(generic.ListView):
    form_class = UserForm
    template_name = "dimagi/userloc.html"

    def get (self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post (self,request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            if request.POST.get('checkin'):
                email = request.POST.get('email')
                city = request.POST.get('city')
                state = request.POST.get('state')
                country = request.POST.get('country')
                t = Tracker()
                try:
                    user = t.get_user(email)
                    city_data = CityFinder().find_city_data(city,state,country)
                    # lookup user and update their record.
                    if city_data:
                        Tracker().update_user_location(user, city, city_data)
                    else:
                        Tracker().update_user_location(user, city, None)
                        print("Couldn't find city data")
                        raise django.forms.ValidationError(f"Couldnt figure out city {city}")
                    # lookup city
                    # store in db
                    return redirect('user-locations')
                except Exception as e:
                    traceback.print_exc()
                    form.errors[django.forms.forms.NON_FIELD_ERRORS] = ErrorList([e.__str__()])
                    return render(request, self.template_name, {'form': form})

dimagi/templates/dimagi/userloc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Location</title>
</head>
<body>
    <form action="." method="POST">
      <h3>Hello.  Please Tell us where you are:</h3>
      <br><br>
      {% csrf_token %}
      {%  if form.errors  %}
        Please correct the error{{ form.errors|pluralize }} below:
        {{ form.all.errors }}
      {% endif %}
      <table>
        {{ form.as_table }}
      </table>
      <br><br>
      <input name='checkin' value="I am checking IN" type="submit"/>
    </form>
</body>
</html>

dimagi/templates/dimagi/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users</title>
</head>
<body>
{% if user_list %}
    <ul>
    {% for user in user_list %}
        <li>{{user.email}} {{ user.city }} {{user.timestamp}} {{user.lat}} {{user.lng}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No users are available.</p>
{% endif %}

<a href="{% url 'user-form'%}">Enter a user location</a>
</body>
</html>